// Generated by https://quicktype.io

export interface ClashUserTag {
    tag:                   string;
    name:                  string | undefined;
    expLevel:              number;
    trophies:              number;
    bestTrophies:          number;
    wins:                  number;
    losses:                number;
    battleCount:           number;
    threeCrownWins:        number;
    challengeCardsWon:     number;
    challengeMaxWins:      number;
    tournamentCardsWon:    number;
    tournamentBattleCount: number;
    role:                  string;
    donations:             number;
    donationsReceived:     number;
    totalDonations:        number;
    warDayWins:            number;
    clanCardsCollected:    number;
    clan:                  Clan | undefined;
    arena:                 Arena;
    leagueStatistics:      LeagueStatistics;
    badges:                Badge[] | undefined;
    achievements:          Achievement[] | undefined;
    cards:                 Card[] | undefined;
    currentDeck:           Card[] | undefined;
    currentFavouriteCard:  CurrentFavouriteCard;
    starPoints:            number;
    expPoints:             number;
}

export interface Achievement {
    name:           string;
    stars:          number;
    value:          number;
    target:         number;
    info:           string;
    completionInfo: null;
}

export interface Arena {
    id:   number;
    name: string;
}

export interface Badge {
    name:     string;
    level:    number;
    maxLevel: number;
    progress: number;
    target:   number;
    iconUrls: BadgeIconUrls;
}

export interface BadgeIconUrls {
    large: string;
}

export interface Card {
    name:       string;
    id:         number;
    level:      number;
    maxLevel:   number;
    count:      number;
    iconUrls:   CardIconUrls;
    starLevel?: number;
}

export interface CardIconUrls {
    medium: string;
}

export interface Clan {
    tag:     string;
    name:    string;
    badgeId: number;
}

export interface CurrentFavouriteCard {
    name:     string;
    id:       number;
    maxLevel: number;
    iconUrls: CardIconUrls;
}

export interface LeagueStatistics {
    currentSeason: CurrentSeason;
}

export interface CurrentSeason {
    trophies:     number;
    bestTrophies: number;
}
