// Generated by https://quicktype.io

export interface Gen1 {
    count?:    number;
    next?:     string;
    previous?: null;
    results?:  Result[];
}

export interface Result {
    name?: string;
    url?:  string;
}
