// Generated by https://quicktype.io

export interface HelperXID {
    base_happiness:         number | undefined;
    capture_rate:           number | undefined;
    color?:                  Color | undefined;
    egg_groups:             Color[] | undefined;
    evolution_chain:        EvolutionChain | undefined;
    evolves_from_species:   null | undefined;
    flavor_text_entries:    FlavorTextEntry[] | undefined;
    form_descriptions:      any[] | undefined;
    forms_switchable:       boolean | undefined;
    gender_rate:            number | undefined;
    genera:                 Genus[] | undefined;
    generation:             Color | undefined;
    growth_rate:            Color | undefined;
    habitat:                Color | undefined;
    has_gender_differences: boolean | undefined;
    hatch_counter:          number | undefined;
    id:                     number | undefined;
    is_baby:                boolean | undefined;
    is_legendary:           boolean | undefined;
    is_mythical:            boolean | undefined;
    name:                   string | undefined;
    names:                  Name[] | undefined;
    order:                  number | undefined;
    pal_park_encounters:    PalParkEncounter[] | undefined;
    pokedex_numbers:        PokedexNumber[] | undefined;
    shape:                  Color | undefined;
    varieties:              Variety[] | undefined;
}

export interface Color {
    name: string | undefined;
    url:  string | undefined;
}

export interface EvolutionChain {
    url: string;
}

export interface FlavorTextEntry {
    flavor_text: string;
    language:    Color;
    version:     Color;
}

export interface Genus {
    genus:    string;
    language: Color;
}

export interface Name {
    language: Color;
    name:     string;
}

export interface PalParkEncounter {
    area:       Color;
    base_score: number;
    rate:       number;
}

export interface PokedexNumber {
    entry_number: number;
    pokedex:      Color;
}

export interface Variety {
    is_default: boolean;
    pokemon:    Color;
}
