// Generated by https://quicktype.io

export interface LolNamePlayer {
    id:            string;
    accountId:     string;
    puuid:         string;
    name:          string;
    profileIconId: number | string | undefined;
    revisionDate:  number;
    summonerLevel: number;
}
